e_APTdata<-function(explaining=0){
if(explaining==0) {
cat(" ## DATA : 부동산 실거래 공개시스템(http://rt.molit.go.kr)", '\n')
cat(" #-----------------------------------------------------------  ", '\n')
cat(" library(readxl) ", '\n')
cat(" options(max.print=1000000) ", '\n')
cat("  ", '\n')
cat(" a15<-read_excel('APT매매경기도2015.xlsx', skip=15)   ", '\n')
cat(" a15<-a15[,c(1:11)]    ", '\n')
cat(" a16<-read_excel('APT매매경기도2016.xlsx', skip=15)    ", '\n')
cat(" a16<-a16[,c(1:11)]   ", '\n')
cat(" a17<-read_excel('APT매매경기도2017.xlsx', skip=15)    ", '\n')
cat(" a17<-a17[,c(1:11)]    ", '\n')
cat(" a18<-read_excel('APT매매경기도2018.xlsx', skip=15)    ", '\n')
cat(" a18<-a18[,c(1:11)]    ", '\n')
cat(" a19<-read_excel('APT매매경기도2019.xlsx', skip=15)    ", '\n')
cat(" a19<-a19[,c(1:11)]    ", '\n')
cat(" a20<-read_excel('APT매매경기도2020.xlsx', skip=15)    ", '\n')
cat(" a20<-a20[,c(1:11)]    ", '\n')
cat(" a21<-read_excel('APT매매경기도2021.xlsx', skip=15)  ", '\n')
cat(" a21<-a21[,c(1:11)]    ", '\n')
cat(" a22<-read_excel('APT매매경기도2022.xlsx', skip=15)  ", '\n')
cat(" a22<-a22[,c(1:11)]    ", '\n')
cat(" a23<-read_excel('APT매매경기도2023.xlsx', skip=15)  ", '\n')
cat(" a23<-a23[,c(1:11)]    ", '\n')
cat("    ", '\n')
cat(" df<-rbind(a15, a16, a17, a18, a19, a20, a21, a22, a23) ", '\n')
cat(" rm(a15, a16, a17, a18, a19, a20, a21, a22, a23) ", '\n')
cat(" df<-df[,c(1, 5:11)] ", '\n')
cat("  ", '\n')
cat(" library(dplyr) ", '\n')
cat(" mylist <- list()   ", '\n')
cat("  ", '\n')
cat(" colnames(df)<-c('시군구','단지명','전용면적','계약년월','계약일','거래금액','층', '건축연도' ) ", '\n')
cat(" df$전용면적<-as.numeric( df$전용면적 ) ", '\n')
cat(" df$평형<- round(df$전용면적/3.3, 0)  ", '\n')
cat("  ", '\n')
cat(" df$거래금액 <- gsub(',', '', df$거래금액)   ", '\n')
cat(" df$거래금액<-as.numeric( df$거래금액 )   ", '\n')
cat(" df$평당매매가<-round(df$거래금액/(df$전용면적/3.3), 0)  ", '\n')
cat("    ", '\n')
cat(" SE_day<-function(Sday, mark=1){   ", '\n')
cat("   if(mark==1) {paste(substring(Sday,1,4), '-', substring(Sday,5,6), '-','01', sep='')}   ", '\n')
cat("   else if(mark==2) {paste(substring(Sday,1,4), '-', substring(Sday,5,6), '-','31', sep='')}   ", '\n')
cat(" }   ", '\n')
cat("    ", '\n')
cat(" ym_data<-sort(unique(df$계약년월))  # 시작 YearMonth    ", '\n')
cat(" start_yearmonth<-ym_data[1]   ", '\n')
cat(" end_yearmonth<-ym_data[length(ym_data)]  # 마지막 YearMonth    ", '\n')
cat("    ", '\n')
cat(" start_yearmonthday<-SE_day(start_yearmonth, 1)   ", '\n')
cat(" end_yearmonthday<-SE_day(end_yearmonth,2)   ", '\n')
cat("    ", '\n')
cat(" elapsed_months <- function(start_date, end_date) {    ", '\n')
cat("   ed <- as.POSIXlt(end_date)    ", '\n')
cat("   sd <- as.POSIXlt(start_date)    ", '\n')
cat("   12 * (ed$year - sd$year) + (ed$mon - sd$mon +1 )   ", '\n')
cat(" }    ", '\n')
cat("    ", '\n')
cat(" total_elapsed_months <- elapsed_months(start_yearmonthday, end_yearmonthday)   ", '\n')
cat("  ", '\n')
cat(" library(dplyr) ", '\n')
cat("  ", '\n')
cat(" ## 시작: 지역 정의  --------------------------------------------- ", '\n')
cat(" aptname <- df%>%filter(grepl('용인수지구 상현동' , 시군구) )  ## 지역 지정 ", '\n')
cat(" ## 끝 : 지역 정의  --------------------------------------------- ", '\n')
cat("  ", '\n')
cat(" Bdata <- aptname ", '\n')
cat(" aptname<-unique(aptname$단지명) ", '\n')
cat(" print(aptname) ", '\n')
cat("    ", "\n")
cat(" print('mylist[[ 번호 ]]에 결과물 저장')", "\n" )
cat("    ", "\n")
cat(" no_data<-length(aptname) ", '\n')
cat("  ", '\n')
cat(" for( counterxx in 1:no_data) {   ", '\n')
cat(" Cdata <-Bdata %>%filter ( grepl(aptname[counterxx], Bdata$단지명 ) ) ", '\n')
cat(" if(nrow(Cdata)==0) {next}   ", '\n')
cat(" summary_data<-Cdata%>%group_by(시군구, 단지명, 평형, 계약년월)%>%summarize( 거래금액평균=mean(거래금액, na.rm=T), 평당매매가평균=mean(평당매매가, na.rm=T), 거래횟수=n(), .groups = 'drop_last' ) ", '\n')
cat(" summary_data<-as.data.frame(summary_data)   ", '\n')
cat("    ", '\n')
cat(" ## 아파트들 중 최소 평형만 골라서 데이터셋을 만들려면    ", '\n')
cat(" ## pyung<-min(unique(summary_data$평형)) 명령문을 사용한다.   ", '\n')
cat(" pyung<-unique(summary_data$평형)   ", '\n')
cat(" pyung_counter<-length(pyung)   ", '\n')
cat("    ", '\n')
cat("   ", '\n')
cat(" ## Cdata의 계약년월에 들어갈 자료 만들기 -- 시작   ", '\n')
cat(" year0 <-as.numeric( substring(start_yearmonth, 1, 4) )   ", '\n')
cat(" month0 <-as.numeric( substring(start_yearmonth, 5, 6) )   ", '\n')
cat("  ", '\n')
cat(" CNT <- total_elapsed_months ## 총개월수인 데, total_elapsed_months를 지정할 때   ", '\n')
cat("  ", '\n')
cat(" timeindex=c()    ", '\n')
cat(" for(i in 1:CNT){    ", '\n')
cat("   month1<-month0    ", '\n')
cat("   if(month1<10) {month1<-paste0('0', month1)}    ", '\n')
cat("   else {month1<-as.character(month1)}    ", '\n')
cat("   TempDate<-as.numeric(paste0(year0, month1))    ", '\n')
cat("      ", '\n')
cat("   timeindex=c(timeindex, TempDate)    ", '\n')
cat("      ", '\n')
cat("   if(month0==12) {year0 <- year0 + 1    ", '\n')
cat("   month0<-0}    ", '\n')
cat("   month0<-month0+1 }    ", '\n')
cat("    ", '\n')
cat(" 평형index<-as.numeric(names(xtabs(~summary_data$평형)))   ", '\n')
cat(" TempCount <- length(평형index)   ", '\n')
cat("    ", '\n')
cat(" Temp<-as.data.frame(matrix(data=rep(c(NA),(TempCount*CNT)*7), ncol=7))    ", '\n')
cat(" colnames(Temp)<-c('시군구','단지명','평형','계약년월','거래금액평균','평당매매가평균', '거래횟수' )    ", '\n')
cat("    ", '\n')
cat(" for(kM in 1:TempCount){    ", '\n')
cat("   alpha <- kM*CNT-(CNT-1)    ", '\n')
cat("   beta <- kM*CNT    ", '\n')
cat("   for(iM  in  alpha: beta ){    ", '\n')
cat("     Temp$단지명[iM] <- aptname[counterxx]    ", '\n')
cat("   }}    ", '\n')
cat("    ", '\n')
cat("    ", '\n')
cat(" for(kM in 1:TempCount){   ", '\n')
cat("   alpha <- kM*CNT-(CNT-1)    ", '\n')
cat("   beta <- kM*CNT    ", '\n')
cat("   for(iM  in  alpha: beta ){    ", '\n')
cat("     Temp$평형[iM] <- 평형index[kM]    ", '\n')
cat("   }}    ", '\n')
cat("    ", '\n')
cat(" for(kM in 1:TempCount){    ", '\n')
cat("   alpha <- kM*CNT-(CNT-1)    ", '\n')
cat("   beta <- kM*CNT    ", '\n')
cat("   for(iM  in  alpha: beta ){    ", '\n')
cat("     Temp$계약년월[iM] <- timeindex[iM-(kM-1)*CNT]    ", '\n')
cat("   }}    ", '\n')
cat("    ", '\n')
cat("  ", '\n')
cat(" TempCount2 <- (TempCount * CNT )  ", '\n')
cat("  ", '\n')
cat(" for( j in 1:TempCount2) {    ", '\n')
cat("   for( i in 1:nrow(summary_data) ) {    ", '\n')
cat("     if( (Temp$평형[j]==summary_data$평형[i] )  &  ( Temp$계약년월[j]==summary_data$계약년월[i] )  ) ", '\n')
cat("     {Temp$평당매매가평균[j] <- summary_data$평당매매가평균[i]     ", '\n')
cat("      Temp$시군구[j] <- summary_data$시군구[i]   ", '\n')
cat("      Temp$거래금액평균[j] <- summary_data$거래금액평균[i]     ", '\n')
cat("      Temp$거래횟수[j] <- summary_data$거래횟수[i] } } }   ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat(" for( ixcount in 0:(TempCount-1) ) { ", '\n')
cat("   if(is.na(Temp$거래금액평균[ixcount*CNT+1])) { ", '\n')
cat("      for(icounter in (ixcount*CNT+2):((ixcount+1)*CNT-1)) { ", '\n')
cat("          if(!is.na(Temp$거래금액평균[icounter])) {break} ", '\n')
cat("          } ", '\n')
cat("      Temp$시군구[ixcount*CNT+1] <- Temp$시군구[icounter] ", '\n')
cat("      Temp$거래금액평균[ixcount*CNT+1] <- Temp$거래금액평균[icounter] ", '\n')
cat("      Temp$평당매매가평균[ixcount*CNT+1] <- Temp$평당매매가평균[icounter] ", '\n')
cat("      Temp$거래횟수[ixcount*CNT+1] <- 0 ", '\n')
cat("   } } ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat(" Temp$시군구<-zoo::na.locf(Temp$시군구) ", '\n')
cat(" Temp$거래금액평균<-zoo::na.locf(Temp$거래금액평균) ", '\n')
cat(" Temp$평당매매가평균<-zoo::na.locf(Temp$평당매매가평균) ", '\n')
cat("  ", '\n')
cat(" mylist[[counterxx]]<-Temp ", '\n')
cat("  ", '\n')
cat(" } ", '\n')
cat("  ", '\n')
}}


