e_ggplot2<-function(explaining=0){

if(explaining==0) {

cat("\033[1;31m# 히스토그램 with jmv and ggplot -------------------\033[0m ", '\n')
cat("  Adata<-interest ", '\n')
cat("  jmv::descriptives(data = interest, vars = LoanInterest, hist=TRUE, dens=TRUE) ", '\n')
cat("  ggplot(data=Adata, aes(x=LoanInterest)) + geom_histogram(bins=40) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# -- geom_point산포도 with ggplot -------\033[0m ", '\n')
cat("  library(dplyr); library(aj412s); library(ggplot2); library(ggthemes) ", '\n')
cat("  Adata<-KoreaMacro ", '\n')
cat("  Adata<-as.data.frame(Adata) ", '\n')
cat("   ", '\n')
cat("  ggplot(data=Adata, aes(x=yearmonth, y=kospi)) + geom_point(size=3) + ", '\n')
cat("      geom_line(col='black') + geom_point(col='steelblue')  + ", '\n')
cat("      labs(x='시간', y='코스피지수', title='코스피지수의 변화', " , '\n')
cat("      subtitle='코스피 인덱스의 시간에 따른 변화 추이 분석',   " , '\n')
cat("      caption='Source: Account' ) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat(" \033[1;31m# -- geom_line직선 with ggplot -------\033[0m ", '\n')
cat(" \033[1;31m# -- linetype : blank, solid, dashed, dotted, dotdash, longdash, twodash -------\033[0m ", '\n')
cat("   ", '\n')
cat(" \033[1;31m# KoreaMacro 변수명 재정의  \033[0m ", '\n')
cat("  colnames(Adata)<-c('index', 'yearmonth', 'currency', 'cd91', 'bond3yr', 'kospi', 'surplus') ", '\n')
cat("   ", '\n')
cat("\033[1;31m# 직선 그리기를 위한 데이터작업 시작 --------\033[0m ", '\n')
cat("  Adata<-mkdate_form(Adata, 2)  ", '\n')
cat("  colnames(Adata)[8]<-'yearmonth2' ", '\n')
cat("  Adata$year<-substring(Adata$yearmonth2, 1,4) ", '\n')
cat("  Adata$month<-substring(Adata$yearmonth2, 6,7) ", '\n')
cat("  Adata$year<-as.numeric(Adata$year) ", '\n')
cat("  Adata$month<-as.numeric(Adata$month) ", '\n')
cat("  코스피<-Adata %>% group_by(year) %>% summarize(KOSPI평균=mean(kospi))  ", '\n')
cat("\033[1;31m# 직선 그리기를 위한 데이터작업 끝남 --------\033[0m ", '\n')
cat("  ", '\n')
cat("  p <- ggplot(data=코스피, aes(x=year, y=KOSPI평균)) +  ", '\n')
cat("  \033[1;31m직선 셋업\033[0m  geom_line(group=1, col='red', linewidth=1) + ", '\n')
cat("  \033[1;31m점 셋업\033[0m    geom_point(col='red', size=3.0) + ", '\n')
cat("  \033[1;31my값 표시\033[0m   geom_text( data=코스피, aes(y=KOSPI평균, label = round(KOSPI평균,0), vjust=-1, size=4) ) + ", '\n')
cat("  \033[1;31mx축값 표시\033[0m theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) + ", '\n')
cat("  \033[1;31my축값 표시\033[0m theme(axis.text.y=element_text(color='black', size=13)) + ", '\n')
cat("  \033[1;31my축값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;31m제목 크기\033[0m  theme(title=element_text(size= 30 , face='bold')) + ", '\n')
cat("  \033[1;31my축명크기\033[0m  theme(axis.title.y = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mx축명크기\033[0m  theme(axis.title.x = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mxy축/제목 타이틀\033[0m labs(x='연도', y='연간 코스피평균', title='연도별 코스피평균') + ", '\n')
cat("  \033[1;31m범례 삭제\033[0m theme(legend.position = 'none') ", '\n')
cat("  \033[1;32m그래프출력\033[0m print(p) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# -- 2개의 직선 그리기 -------\033[0m ", '\n')
cat("library(ggplot2); library(ggthemes) ", '\n')
cat("  x = 1:5; y1 = c(2, 4, 6, 8, 10); y2 = c(1, 3, 5, 7, 9)  ", '\n')
cat("  Adata <- data.frame( x, y1, y2 ) ", '\n')
cat("   ", '\n')
cat("  ggplot(Adata, aes(x = x)) + ", '\n')
cat("      geom_line(aes(y = y1), color = 'blue', linetype = 'solid') + ", '\n')
cat("      geom_line(aes(y = y2), color = 'red',  linetype = 'dashed')  ", '\n')
cat("      labs(   ", '\n')
cat("          title = 'Two Lines on One Graph', ", '\n')
cat("          x = 'X-axis Label', ", '\n')
cat("          y = 'Y-axis Label' ) + ", '\n')
cat("      theme_stata(scheme='s1color')  ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  data <- data.frame( ", '\n')
cat("    category = c('A', 'B', 'C', 'D', 'E'), ", '\n')
cat("    value = c(10, 25, 15, 30, 20) ", '\n')
cat("    ) ", '\n')
cat("  ggplot(data, aes(x=reorder(category, value), y = value, fill = value)) + ", '\n')
cat("       geom_bar(stat = 'identity') + ", '\n')
cat("       scale_fill_gradientn(colours = c( 'lightblue', 'darkblue')) + ", '\n')
cat("       theme_minimal() + ", '\n')
cat("       labs(title = '다중 색상 그라데이션 막대 그래프', ", '\n')
cat("            x = '카테고리',  ", '\n')
cat("            y = '값') ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m# 막대그래프 with ggplot -------- \033[0m ", '\n')
cat("\033[1;32m# X축을 factor로 지정해야만 X값이 지정한 순서대로 출력됨  \033[0m ", '\n')
cat("\033[1;32m# 막대그래프 오름차순: ggplot(data=경상수지, aes(x=reorder(year, -경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat("\033[1;32m# 막대그래프 내림차순: ggplot(data=경상수지, aes(x=reorder(year, 경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat("   ", '\n')
cat("library(ggplot2) ", '\n')
cat("  xx <- c('30세이하', '30대', '40대', '50대', '60세이상') ", '\n')
cat("  yy <- c(90.6, 81.5, 73.2, 69.4, 65) ", '\n')
cat("  Adata<-data.frame(xx,yy) ", '\n')
cat("\033[1;31m# X축을 factor로 지정해야만 X값이 지정한 순서대로 출력된다 \033[0m ", '\n')
cat("  Adata$xx <- factor(Adata$xx,levels=c('30세이하','30대','40대','50대','60세이상')) ", '\n')
cat("   ", '\n')
cat("  ggplot(data=Adata, aes(x=xx, y=yy, fill='steelblue')) +  ", '\n')
cat("  \033[1;32m셋업\033[0m       theme_bw() +  ", '\n')
cat("  \033[1;32m셋업\033[0m       geom_bar(stat='identity', col='black', width=0.7) +  ", '\n')
cat("  \033[1;32mX값\033[0m        theme(axis.text.x=element_text(size= 16 , angle=-40) ) + ", '\n')
cat("  \033[1;32mY값\033[0m        theme(axis.text.y=element_text(size= 16) ) + ", '\n')
cat("  \033[1;32mY값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;32m제목\033[0m       labs(title='연도별 경상수지', x='연도', y='경상수지') + ", '\n')
cat("  \033[1;32m제목 크기\033[0m  theme(title=element_text(size=26 , face='bold')) + ", '\n')
cat("  \033[1;32mX축명크기\033[0m  theme(axis.title.x = element_text(size= 20 , face='bold')) + ", '\n')
cat("  \033[1;32mY축명크기\033[0m  theme(axis.title.y = element_text(size= 20 , face='bold')) + ", '\n')
cat("  \033[1;32m막대숫자\033[0m   geom_text(data=Adata, aes(y=yy, label = round(yy, 0) , vjust=-1, size=15) ) + ", '\n')
cat("  \033[1;32m범례삭제\033[0m   theme(legend.position = 'none') + ", '\n')
cat("  \033[1;32mY축범위\033[0m    ylim(0, 100)  ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# facet_wrap의 활용 --------\033[0m ", '\n')
cat("  발<-c(235,222,235, 241,251,226, 274,282,291, 260,272,282) ", '\n')
cat("  키<-c(142,163,163, 165,171,167, 174,179,161, 187,189,178) ", '\n')
cat("  성별<-c('남','남','남', '남','남','남', '여','여','여', '여','여','여') ", '\n')
cat("  Adata <- as.data.frame( cbind(발, 키, 성별)) ", '\n')
cat("  p <- ggplot(Adata, aes(x=발, y=키) ) + ", '\n')
cat("        geom_point(col='blueviolet', size=2) +", '\n')
cat("        labs(x='발크기', y='신장', title='성별에 따른 발크기와 신장') +", '\n')
cat("        facet_wrap(~성별) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# 백그라운드를 만들어 지정하기 -------- \033[0m ", '\n')
cat("  p + theme(panel.background = element_rect(fill = 'white', color = 'black'),  ", '\n')
cat("          panel.grid.major = element_line(color = 'black', linetype = 'dotted'), ", '\n')
cat("          panel.grid.minor = element_line(color = 'black',  linetype = 'dotted' )) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# Panel Data --------\033[0m    ", '\n')
cat("  library(gplots); library(plm)    ", '\n')
cat("  Grunfedl<-data(package='plm', 'Grunfeld')    ", '\n')
cat("  Gdata<-Grunfeld    ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$firm)   ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$year)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m# 시계열분석 --------\033[0m ", '\n')
cat("  library(forecast) ", '\n')
cat("  AccountBalance <- ts(AccountBalance, start=c(2015,1), frequency=4) ", '\n')
cat("  \033[1;32m# autoplot \033[0m  autoplot(AccountBalance[ ,c('export','profit')], facets=TRUE )  # forecast패키지  \033[0m", '\n') 
cat("  \033[1;32m# ggseasonplot \033[0m  ggseasonplot(AccountBalance[,'import'], year.labels = TRUE, year.labels.left=TRUE)  # forecast패키지  \033[0m", '\n')
cat("  \033[1;32m# ggsubseriesplot \033[0m  ggsubseriesplot(AccountBalance[,'export'])  # forecast패키지  \033[0m", '\n')
cat("  ", '\n')

}}