e_ggplot1<-function(explaining=0){

if(explaining==0) {

cat("\033[1;31m # ---- 산포도 with scatr -------------------\033[0m ", '\n')
cat("\033[1;31m ## 막대그래프: 변수 1개 -------------------------------------- \033[0m    ", '\n')
cat(" library(bss2); library(dplyr); library(ggplot2); library(ggthemes)   ", '\n')
cat(" Adata<-BasicData   ", '\n')
cat(" colnames(Adata)   ", '\n')
cat(" Adata<-Adata[complete.cases(Adata), ]   ", '\n')
cat(" ggplot(data=Adata, aes(x=conv)) + geom_bar(fill='salmon3', stat='count')   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## 막대그래프: 변수 2개 ------------------------------------------------- \033[0m  ", '\n')
cat(" library(ggplot2); library(ggthemes)   ", '\n')
cat("    ", '\n')
cat(" ggplot2에서 stat = 'identity'는 y축의 값을 데이터의 실제 값으로 설정하는 명령어입니다.     ", '\n')
cat(" 기본적으로 geom_bar()는 stat = 'count'를 사용하여 각 범주의 빈도를 계산하고     ", '\n')
cat(" 이를 y축 값으로 사용합니다. 그러나 stat = 'identity'를 사용하면 데이터셋에 있는     ", '\n')
cat(" y축 값을 그대로 사용하여 막대그래프를 그립니다.   ", '\n')
cat("    ", '\n')
cat(" ggplot(data=your_data, aes(x = your_categorical_variable, y=your_numeric_variable)) +   ", '\n')
cat("   geom_bar(stat = 'identity')   ", '\n')
cat("    ", '\n')
cat(" 위 예제 코드는 x축에 범주형 변수를, y축에 수치형 변수를 사용하여 막대그래프를 그립니다   ", '\n')
cat(" stat = 'identity'를 사용함으로써 y축 값이 데이터셋의 실제 값으로 설정됩니다.   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## 막대그래프: 변수 2개 --------  \033[0m  ", '\n')
cat("\033[1;31m < 예제1 : x변수와 y변수 >  \033[0m ", '\n')
cat(" Adata<-BasicData   ", '\n')
cat(" tmp1<-Adata %>% group_by(nfamily) %>% summarize(소득평균=mean(inc))   ", '\n')
cat(" ggplot(data=tmp1, aes(x=nfamily, y=소득평균)) +    ", '\n')
cat("    geom_bar(stat='identity', fill='salmon')   ", '\n')
cat("    ", '\n')
cat("\033[1;31m < 예제2 : x변수와 x변수의 빈도수 > \033[0m  ", '\n')
cat(" tmp2<-xtabs(~Adata$satprice)   ", '\n')
cat(" tmp2<-as.data.frame(tmp2)   ", '\n')
cat(" colnames(tmp2)<-c('satprice', '빈도수')   ", '\n')
cat(" ggplot(data=tmp2, aes(x=satprice, y=빈도수)) +    ", '\n')
cat("    theme_bw() +   ", '\n')
cat("    geom_bar(stat='identity', fill='salmon', col='black')   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## 막대그래프: 변수는 3개 -------- \033[0m  ", '\n')
cat(" tmp1<-xtabs(~Adata$gpa + Adata$gender)   ", '\n')
cat(" tmp1<-as.data.frame(tmp1)   ", '\n')
cat(" index<-c(1:3)   ", '\n')
cat(" tmp1[ ,index]<-lapply(tmp1[,index], as.numeric)   ", '\n')
cat(" colnames(tmp1)<-c('gpa', 'gender' , 'freq')   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## 범주형 변수는 factor로 지정. 그렇지 않으면 연속형 변수로 인식할 수 있음 \033[0m  ", '\n')
cat(" tmp1$gender<-as.factor(tmp1$gender)   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## 옆으로 배열--------------------------------------------------  \033[0m ", '\n')
cat(" ggplot(data=tmp1, aes(x=gpa, y=freq, fill=gender)) +   ", '\n')
cat("   geom_bar(stat='identity', position='dodge', col='black') +   ", '\n')
cat("   labs(title='Position=dodoge') + theme_bw()   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## 비율 ------------------------------------------------------- \033[0m  ", '\n')
cat(" ggplot(data=tmp1, aes(x=gpa, y=freq, fill=gender)) +   ", '\n')
cat("   geom_bar(stat='identity', position='fill', col='black') +   ", '\n')
cat("   labs(title='Position=fill') + theme_bw()   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## 위로 쌓기 -------------------------------------------------- \033[0m  ", '\n')
cat(" ggplot(data=tmp1, aes(x=gpa, y=freq, fill=gender)) +   ", '\n')
cat("   geom_bar(stat='identity', position='stack', col='black') +   ", '\n')
cat("   labs(title='Position=stack') + theme_bw()   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## 막대그래프의 x축과 y축의 위치 변경하기 --------------------- \033[0m  ", '\n')
cat(" ggplot(data=tmp1, aes(x=reorder(gpa, freq), y=freq, fill=gender)) +   ", '\n')
cat("   geom_bar(stat='identity', position='stack', col='black') +   ", '\n')
cat("   labs(title='Position=stack') + theme_bw() + coord_flip()   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## 섬세한 막대그래프 그리기  -------------------------------  \033[0m ", '\n')
cat(" library(bss2); library(dplyr); library(ggplot2)   ", '\n')
cat("\033[1;31m ## 대표자 연령 및 매출  \033[0m ", '\n')
cat(" Adata<-opencsv('21년_천안시_전통시장_데이터.csv', header=F, skip=1)   ", '\n')
cat(" Adata<-xtabs(~Adata$V46+Adata$V50)   ", '\n')
cat(" df<-as.data.frame(Adata)   ", '\n')
cat(" colnames(df)<-c('대표자연령', '매출액', '빈도수')   ", '\n')
cat(" df$대표자연령<-as.numeric(df$대표자연령)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m # 그래프에 원하는 배열 순서대로  점포명 앞에 A, B, C ...알파벳 포함하기  \033[0m ", '\n')
cat("\033[1;31m # 알파벳을 않붙이면 가나다라..순서대로 배열됨  \033[0m ", '\n')
cat("\033[1;31m # 그런데, 연령대는 숫자이기 때문에 숫자 순서대로 정렬되므로 알파벳을 않붙여도 됨 \033[0m  ", '\n')
cat(" df$대표자연령[df$대표자연령==1]<-'<30대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==2]<-'<40대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==3]<-'<50대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==4]<-'<60대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==5]<-'<70대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==6]<-'>70대'   ", '\n')
cat("    ", '\n')
cat("\033[1;31m # legend 표시는 작은순서대로 배열되므로 \033[0m   ", '\n')
cat("\033[1;31m # 5천만원은 0.5억원으로 표시  \033[0m ", '\n')
cat(" df$매출액<-as.numeric(df$매출액)   ", '\n')
cat(" df$매출액[df$매출액==1]<-'<0.5억원'   ", '\n')
cat(" df$매출액[df$매출액==2]<-'<1억원'   ", '\n')
cat(" df$매출액[df$매출액==3]<-'<2억원'   ", '\n')
cat(" df$매출액[df$매출액==4]<-'<3억원'   ", '\n')
cat(" df$매출액[df$매출액==5]<-'>3억원'   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat(" ggplot(data=df, aes(x=대표자연령, y=빈도수, fill=매출액)) +    ", '\n')
cat("   theme_bw() +   ", '\n')
cat("   geom_bar(stat='identity', position='dodge') +   ", '\n')
cat("   scale_fill_manual(values = c( '<0.5억원' = 'magenta1',    ", '\n')
cat("                                 '<1억원' ='magenta2',   ", '\n')
cat("                                 '<2억원'='magenta3',    ", '\n')
cat("                                 '<3억원'='magenta4',   ", '\n')
cat("                                 '>3억원'='deeppink4')) +   ", '\n')
cat("   \033[1;31m# 차트 제목 위치를 우측으로 옮기기  \033[0m ", '\n')
cat("   \033[1;31m# hjust지정없으면 맨 왼쪽에 배열 \033[0m  ", '\n')
cat("   theme(plot.title=element_text(hjust = 0.5)) +   ", '\n')
cat("   labs(x='대표자 연령', y='빈도수', title='매출액 분포') +   ", '\n')
cat("   theme(title=element_text(size= 30 , face='bold')) +   ", '\n')
cat("   \033[1;31m# X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기  \033[0m ", '\n')
cat("   theme(axis.title.x = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-20, vjust=0.3)) +   ", '\n')
cat("   \033[1;31m# Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  \033[0m ", '\n')
cat("   theme(axis.title.y = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +   ", '\n')
cat("   \033[1;31m# Y축의 숫자를 3자리씩 끊어서 콤마를 표시  \033[0m ", '\n')
cat("   scale_y_continuous(labels =scales:: comma) +     ", '\n')
cat("   \033[1;31m# 범례의 타이틀 크기 및 범례 숫자 크기 \033[0m  ", '\n')
cat("   theme(legend.title = element_text(size = 15)) +   ", '\n')
cat("   theme(legend.text = element_text(size = 13))   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat(" ggplot(data=tmp1, aes(x=gpa, y=freq, fill=gender)) +   ", '\n')
cat("   theme_bw() +   ", '\n')
cat("\033[1;31m # 타이틀명 및 타이틀의 폰트 크기  \033[0m ", '\n')
cat("   geom_bar(stat='identity', position='dodge', col='black') +   ", '\n')
cat("   labs(x='학점GPA', y='빈도수', title='성별에 따른 학점GPA') +   ", '\n')
cat("   theme(title=element_text(size= 30 , face='bold')) +   ", '\n')
cat("\033[1;31m # X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기  \033[0m ", '\n')
cat("   theme(axis.title.x = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) +   ", '\n')
cat("\033[1;31m # Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  \033[0m ", '\n')
cat("   theme(axis.title.y = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +   ", '\n')
cat("\033[1;31m # Y축의 숫자를 3자리씩 끊어서 콤마를 표시 \033[0m  ", '\n')
cat("   scale_y_continuous(labels =scales:: comma) +     ", '\n')
cat("\033[1;31m # 범례의 타이틀 크기 및 범례 숫자 크기  \033[0m ", '\n')
cat("   theme(legend.title = element_text(size = 15)) +   ", '\n')
cat("   theme(legend.text = element_text(size = 13)) +   ", '\n')
cat("\033[1;31m # 막대그래프의 색깔을 지정  \033[0m ", '\n')
cat(" scale_fill_manual(values = c( '1' = 'salmon', '2' ='cyan4'))   ", '\n')
cat("    ", '\n')
cat("\033[1;31m ## line graph의 색깔 지정하기  --------- \033[0m  ", '\n')
cat(" ggplot(df, aes(x = time, y = prob, color = 직업변화)) +    ", '\n')
cat("   geom_line(lwd=2, lty='dashed') + theme_bw() +   ", '\n')
cat("   scale_color_manual(values =    ", '\n')
cat("    c( '제조->서비스' = 'blue',    ", '\n')
cat("       '전기->서비스' = 'black',    ", '\n')
cat("       '연구->서비스' = 'red'))   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## line graph 그리기  --------- \033[0m  ", '\n')
cat(" library(ggplot2)   ", '\n')
cat(" df<-openxlsx('ggplot_line_example.xlsx', header=T)   ", '\n')
cat(" ggplot(df, aes(x = time, y = prob, color = 직업변화)) +     ", '\n')
cat("   theme_bw() +   ", '\n')
cat("   geom_line(size=2, linetype='dashed') +   ", '\n')
cat("   labs(x='시간', y='확률', title='시간 변화에 따른 직업변환') +   ", '\n')
cat("   theme(title=element_text(size= 30 , face='bold')) +   ", '\n')
cat("\033[1;31m # X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기 \033[0m  ", '\n')
cat("   theme(axis.title.x = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) +   ", '\n')
cat("\033[1;31m # Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  \033[0m ", '\n')
cat("   theme(axis.title.y = element_text(size= 25 ,face='bold')) +     ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +   ", '\n')
cat("\033[1;31m # Y축의 숫자를 3자리씩 끊어서 콤마를 표시  \033[0m ", '\n')
cat("   scale_y_continuous(labels =scales:: comma) +     ", '\n')
cat("\033[1;31m # 범례의 타이틀 크기 및 범례 숫자 크기  \033[0m ", '\n')
cat("   theme(legend.title = element_text(size = 15)) +   ", '\n')
cat("   theme(legend.text = element_text(size = 13)) +   ", '\n')
cat("\033[1;31m # 선의 색깔을 지정  \033[0m ", '\n')
cat("   scale_color_manual(values = c( '제조->서비스' = 'blue',    ", '\n')
cat(" 				'전기->서비스' = 'black', '연구->서비스' = 'red'))   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
e_mlogit<-function(explaining=0){
if(explaining==0) {
cat(" \033[1;34m## multinomial logit 분석 ------ \033[0m", '\n')
cat(" library(nnet); library(dplyr); library(bss2) ", '\n')
cat(" ", '\n')
cat(" set.seed(123) ", '\n')
cat(" n <- 1000 ", '\n')
cat(" data <- data.frame( ", '\n')
cat(" debt_type = sample(c('부채없음', '저당대출', '신용대출', '가족대출'), n, replace = TRUE), ", '\n')
cat(" gender = sample(c('남성', '여성'), n, replace = TRUE), ", '\n')
cat(" age = sample(20:70, n, replace = TRUE), ", '\n')
cat(" income = rnorm(n, mean = 5000, sd = 2000) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;31m# Base가 될 독립변수의 유형 지정 --------- \033[0m", '\n')
cat(" data$debt_type<-as.factor(data$debt_type) ", '\n')
cat(" data$debt_type <- relevel(data$debt_type, ref = '부채없음') ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# multinom 모델 적합 --------- \033[0m", '\n')
cat(" result <- multinom(debt_type ~ gender + age + income, data = data, subset=c(gender==1)) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 분석결과 보기 --------- \033[0m", '\n')
cat(" summary_mlogit(result) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 소득변화에 따른 확률을 보기 위한 임의 자료 -------- \033[0m", '\n')
cat(" new_data <- data.frame( ", '\n')
cat(" gender = rep('남성', 61), ", '\n')
cat(" age = rep(30, 61), ", '\n')
cat(" income = seq(2000, 8000, 100) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 확률 계산 --------- \033[0m", '\n')
cat(" prob_result <- mlogit_prob(model, new_data) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 결과 출력 --------- \033[0m", '\n')
cat(" print(prob_result) ", '\n')
cat(" ", '\n')
}}

cat("\033[1;31m ## dotchart 그리기  ---------------------------------  \033[0m ", '\n')
cat(" library(bss2); library(dplyr); library(ggplot2); library(ggthemes)   ", '\n')
cat(" Adata<-BasicData   ", '\n')
cat(" colnames(Adata)   ", '\n')
cat(" re<-lm(expend~inc+nfamily+gender, data=Adata)   ", '\n')
cat(" ols_pred(re) 또는, lm_pred(re)  ", '\n')
cat("    ", '\n')
cat(" x<-c('소득', '가구원수', '성별')   ", '\n')
cat("    ", '\n')
cat(" # ols_pred 또는, lm_pred로 구한 값   ", '\n')
cat(" y<-c(569, 463, 456)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m# 컬러를 구현하기 위한 독립변수와 대응되는 그룹명을 임의로 지정 ------- \033[0m ", '\n')
cat(" group<-c('A1', 'A2', 'A3')    ", '\n')
cat(" dataset<-cbind(x, y, group)   ", '\n')
cat(" dataset<-as.data.frame(dataset)   ", '\n')
cat(" dataset$y<-as.numeric(dataset$y)   ", '\n')
cat(" dataset$group<-as.factor(dataset$group)   ", '\n')
cat("    ", '\n')
cat(" dataset$color[dataset$group=='A1']<-'blue'   ", '\n')
cat(" dataset$color[dataset$group=='A2']<-'red'   ", '\n')
cat(" dataset$color[dataset$group=='A3']<-'steelblue'   ", '\n')
cat("    ", '\n')
cat(" dotchart(dataset$y,   ", '\n')
cat("         labels=dataset$x,   ", '\n')
cat("          groups=dataset$group,   ", '\n')
cat("          gcolor='black',   ", '\n')
cat("          color=dataset$color,   ", '\n')
cat("          pch=19,   ", '\n')
cat("          cex=1.3,   ", '\n')
cat("          cex.main=1.5,   ", '\n')
cat("          main='독립변수 변화에 따른 소비지출 변화',   ", '\n')
cat("          xlab='소비지출'   ", '\n')
cat("          )   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat(" p <- dotchart(dataset$y,   ", '\n')
cat("         labels=dataset$x,   ", '\n')
cat("          groups=dataset$group,   ", '\n')
cat("          gcolor='black',   ", '\n')
cat("          color=dataset$color,   ", '\n')
cat("          pch=19,   ", '\n')
cat("          cex=1.3,   ", '\n')
cat("          cex.main=1.5,   ", '\n')
cat("          main='독립변수 변화에 따른 소비지출 변화',   ", '\n')
cat("          xlab='소비지출'   ", '\n')
cat("          )   ", '\n')
cat("    ", '\n')
cat(" p + abline(v=464, lty = 'dashed', lwd=2, col = 'blue') +    ", '\n')
cat("     text(x = 464, y = 2, labels = 'Base Line', pos = 4, col = 'blue', srt = 90)   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## 히트맵 그리기 ----------- \033[0m    ", '\n')
cat(" library(pheatmap)   ", '\n')
cat(" pheatmap(tmp_0, color = colorRampPalette(c('white', 'blueviolet'), cluster_rows = FALSE, cluster_cols = FALSE) )   ", '\n')
cat(" pheatmap(tmp_4, color = colorRampPalette(c('white', 'blueviolet'), cluster_rows = FALSE, cluster_cols = FALSE) )    ", '\n')
cat("    ", '\n')
cat("\033[1;31m## 파이차트 그리기 ----------- \033[0m   ", '\n')
cat("\033[1;31m## piechart1: 대표자 연령 분포  \033[0m ", '\n')
cat(" library(ggplot2); library(bss2); library(dplyr)   ", '\n')
cat(" Adata<-opencsv('2021년_엄태민_데이터.csv', header=F, skip=1)   ", '\n')
cat(" Adata<-xtabs(~Adata$V46)   ", '\n')
cat(" df<-as.data.frame(Adata)   ", '\n')
cat(" colnames(df)<-c('대표자연령', '빈도수')   ", '\n')
cat(" df$대표자연령<-as.numeric(df$대표자연령)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m# 그래프에 원하는 배열 순서대로  점포명 앞에 A, B, C ...알파벳 포함하기  \033[0m ", '\n')
cat("\033[1;31m# 알파벳을 않붙이면 가나다라..순서대로 배열됨  \033[0m ", '\n')
cat("\033[1;31m# 그런데, 연령대는 숫자이기 때문에 숫자 순서대로 정렬되므로 알파벳을 않붙여도 됨 \033[0m ", '\n')
cat("    ", '\n')
cat(" df$대표자연령[df$대표자연령==1]<-'20대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==2]<-'30대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==3]<-'40대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==4]<-'50대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==5]<-'60대'   ", '\n')
cat(" df$대표자연령[df$대표자연령==6]<-'70대'   ", '\n')
cat(" round(df$빈도수/sum(df$빈도수)*100, 0)   ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m ## x에 변수명 입력이 없음  ------------- \033[0m  ", '\n')
cat(" ggplot(df, aes(x = '', y=빈도수, fill = 대표자연령)) +   ", '\n')
cat("   geom_bar(stat='identity', width=1) +   ", '\n')
cat("   coord_polar(theta = 'y', start=0) +   ", '\n')
cat("   ggtitle('대표자 연령의 분포') +   ", '\n')
cat("   geom_col(color = 'black') +   ", '\n')
cat("    ", '\n')
cat("\033[1;31m   ## position_fill vs position_stack \033[0m  ", '\n')
cat("\033[1;31m   # 차트 내부 숫자 크기를 10으로 하는 경우  \033[0m ", '\n')
cat("   geom_text(aes(label = c('20대 슬래쉬n 7%', '30대 슬래쉬n 18%', '40대 슬래쉬n 22%', '50대 슬래쉬n 23%',   ", '\n')
cat("                           '60대 슬래쉬n 22%', '70대 슬래쉬n 7%')),    ", '\n')
cat(" 			         position = position_stack(vjust = 0.5), size=5) +   ", '\n')
cat("   labs(x='', y='') +   ", '\n')
cat("\033[1;31m   #차트 제목 위치를 우측으로 옮기기   \033[0m", '\n')
cat("   theme(plot.title=element_text(hjust = 0.5)) +   ", '\n')
cat("\033[1;31m   #차트 제목 크기를 조정하기  \033[0m ", '\n')
cat("   theme(plot.title=element_text(size = 25.3)) +   ", '\n')
cat("\033[1;31m   #차트 제목 색깔을 조정하기  \033[0m ", '\n')
cat("   theme(plot.title=element_text(colour = 'black')) +   ", '\n')
cat("\033[1;31m   #차트 legend범례 크기를 18로 하는 경우 \033[0m  ", '\n')
cat("   theme(legend.text = element_text(size = 18)) +   ", '\n')
cat("   theme(legend.title = element_text(size = 18))    ", '\n')
cat("       ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("   library(ggplot2)    ", '\n')
cat("   mtcars$car = row.names(mtcars)    ", '\n')
cat("\033[1;31m   # 자동차별 “miles per gasoline”을 히스토그램을 사용해 그리기  \033[0m  ", '\n')
cat("   p<-ggplot(mtcars, aes(x=car, y=mpg, fill=mpg)) +    ", '\n')
cat("     geom_histogram(width=1, stat='identity') +     ", '\n')
cat("     theme_light() +    ", '\n')
cat("     scale_fill_gradient(low='red', high='white', limits=c(5,40)) +    ", '\n')
cat("     theme(axis.title.y=element_text(angle=0)) +     ", '\n')
cat("     theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1))    ", '\n')
cat("       ", '\n')
cat("   print(p)    ", '\n')
cat("\033[1;31m   ## mpg값의 범위가 5~40이므로 lmits을 4~50으로 설정함  \033[0m  ", '\n')
cat("       ", '\n')
cat("   p + coord_polar()    ", '\n')
cat("       ", '\n')
cat("   p + coord_polar() + aes(x=reorder(car, mpg)) +    ", '\n')
cat("     theme(axis.text.x = element_text(angle=-20))    ", '\n')
}
}