e_ggplot3<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("library(ggplot2); library(car); library(lattice); library(gridExtra); library(scatr) ", '\n')
cat("  ", '\n')
cat("\033[1;31m# ---- 산포도 with scatr -------------------\033[0m ", '\n')
cat("  df<-KoreaMacro ", '\n')
cat("  scatr::scat(data=KoreaMacro, x='경상수지', y='kospi') ", '\n')
cat("  scatr::scat(data=df, x='경상수지', y='kospi', line='smooth', se=TRUE) ", '\n')
cat("  scatr::scat(data=df, x='index00', y='경상수지', line='smooth', se=TRUE) ", '\n')
cat("  ", '\n')
cat("\033[1;31m# ---- Line Graph 그리기 -------------------\033[0m ", '\n')
cat("  Bdata<-interest ", '\n')
cat("  ggplot(data=Bdata,aes(x=index,y=LoanInterest)) + geom_line() + theme_bw() ", '\n')
cat("  ", '\n')
cat("\033[1;31m# jmv를 이용해 ‘Bdata일반신용대출금리’를 histogram으로 그리기 ------ \033[0m ", '\n')
cat("  jmv::descriptives(data = Bdata, vars = LoanInterest, hist = T) ", '\n')
cat("  ", '\n')
cat("ggplot(data=mtcars, aes(x=wt, y=mpg)) +  ", '\n')
cat("  geom_point(pch=17, color='blue', size=2) +  ", '\n')
cat("  geom_smooth(method='lm', color='red', linetype=2) + ", '\n')
cat("  labs(title='Automobile Data', x='Weight', y='Miles Per Gallon') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Label Definition and Facet Grid -------\033[0m ", '\n')
cat("  mtcars$am <- factor( mtcars$am, levels=c(0,1),  labels=c('Automatic', 'Manual') ) ", '\n')
cat("  mtcars$vs <- factor( mtcars$vs, levels=c(0,1), labels=c('V-Engine', 'Straight Engine') ) ", '\n')
cat("  mtcars$cyl <- factor(mtcars$cyl) ", '\n')
cat(" ", '\n')
cat("  ggplot(data=mtcars, aes(x=hp, y=mpg, shape=cyl, color=cyl)) + ", '\n')
cat("    geom_point(size=3) +  ", '\n')
cat("    facet_grid(am~vs) +  ", '\n')
cat("    labs(title='Automobile Data by Engine Type', x='Horsepower', y='Miles Per Gallon') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Box plot / Geom Point / Geom Rug ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=rank, y=salary)) + ", '\n')
cat("    geom_boxplot(fill='cornflowerblue',color='black', notch=TRUE) + ", '\n')
cat("    geom_point(position='jitter', color='blue', alpha=0.5) + ", '\n')
cat("    geom_rug(color='black') ", '\n')
cat(" ", '\n')
cat("  ggplot(singer, aes(x=voice.part, y=height)) + ", '\n')
cat("    geom_violin(fill='lightblue') + ", '\n')
cat("    geom_boxplot(fill='lightgreen', width=.2) + ", '\n')
cat(" ", '\n')
cat("  library(lattice) # Singers data  ", '\n')
cat("    ggplot(singer, aes(x=voice.part, y=height)) + geom_boxplot() ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Legend Usage ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=yrs.since.phd, y=salary, color=rank, shape=sex)) + ", '\n')
cat("    geom_point()  ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Overlap-Drawing three density functions ------\033[0m ", '\n') 
cat("  ggplot(data=Salaries, aes(x=salary, fill=rank)) + ", '\n')
cat("    geom_density(alpha=.3) ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Barplot Count : Stacking ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("    geom_bar(position='stack') + ", '\n')
cat("    labs(title='position=stack') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Barplot Count : Side Arrange ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("    geom_bar(position='dodge') + ", '\n')
cat("    labs(title='position=dodge') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Barplot Percent ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=rank, fill=sex)) + ", '\n')
cat("    geom_bar(position='fill') + ", '\n')
cat("    labs(title='position=fill') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Facet Wrap : facet_wrap(~var, nrow=n) ------\033[0m ", '\n')
cat("  library(lattice) ", '\n')
cat("  ggplot(data=singer, aes(x=height)) + ", '\n')
cat("    geom_histogram() + ", '\n')
cat("    facet_wrap(~voice.part, nrow=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Facet Grid ------\033[0m ", '\n')
cat("    # facet_grid(rowvar~colvar) ", '\n')
cat("    # facet_grid(rowvar~.) ", '\n')
cat("    # facet_grid(.~colvar) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Facet Grid1 ------\033[0m ", '\n')
cat("  ggplot(Salaries, aes(x=yrs.since.phd, y=salary, color=rank, shape=rank)) +  ", '\n')
cat("    geom_point() +  ", '\n')
cat("    facet_grid(.~sex) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Facet Grid2 ------\033[0m ", '\n')
cat("  ggplot(data=singer, aes(x=height, fill=voice.part)) + ", '\n')
cat("    geom_density() + ", '\n')
cat("    facet_grid(voice.part~.) ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Point and Lines ------\033[0m ", '\n')
cat("  ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, ", '\n')
cat("    linetype=sex, shape=sex, color=sex)) + ", '\n')
cat("    geom_smooth(method=lm, formula=y~poly(x,2), se=FALSE, size=1) + ", '\n')
cat("    geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# Y-axis Scale and X-axis Label ------\033[0m ", '\n')
cat("  ggplot(data=Salaries, aes(x=rank, y=salary, fill=sex)) + ", '\n')
cat("    geom_boxplot() + ", '\n')
cat("    scale_x_discrete(breaks=c('AsstProf', 'AssocProf', 'Prof'),  ", '\n')
cat("                   labels=c('Assistant_Professor', ", '\n')
cat("                            'Associate_Professor', ", '\n')
cat("                            'Full_Professor')) + ", '\n')
cat("    scale_y_continuous(breaks=c(50000, 100000, 150000, 200000), ", '\n')
cat("                     labels=c('$50K', '$100K', '$150K', '$200K')) + ", '\n')
cat("    labs(title='Faculty Salary by Rank and Sex', x='', y='') ", '\n')
cat(" ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Bubble Chart ------\033[0m ", '\n')
cat("  ggplot(mtcars, aes(x=wt, y=mpg, size=disp)) + ", '\n')
cat("     geom_point(shape=21, color='black', fill='cornsilk') + ", '\n')
cat("     labs(x='Weight', y='Miles Per Gallon', title='Bubble Chart', size='Engine\nDisplacement') ", '\n')
cat(" ", '\n')
cat("\033[1;31m# colors : Set1, Set2, Set3, Pastel1, Pastel2, Paired, Dark2, Accent ------\033[0m ", '\n')
cat("  ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, color=rank)) + ", '\n')
cat("    scale_color_brewer(palette='Accent') + ", '\n')
cat("    geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# colors : My definition ------\033[0m ", '\n') 
cat("  ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary, color=rank)) + ", '\n')
cat("    scale_color_manual(values=c('orange', 'olivedrab', 'navy')) + ", '\n')
cat("    geom_point(size=2) ", '\n')
cat(" ", '\n')
cat("\033[1;31m# gridExtra:: Multiple graphs per page ------\033[0m ", '\n')
cat("  p1 <- ggplot(data=Salaries, aes(x=rank)) + geom_bar()  ", '\n')
cat("  p2 <- ggplot(data=Salaries, aes(x=sex)) + geom_bar()  ", '\n')
cat("  p3 <- ggplot(data=Salaries, aes(x=yrs.since.phd, y=salary)) + geom_point() ", '\n')
cat("  gridExtra::grid.arrange(p1, p2, p3, ncol=3) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" ", '\n')
cat("\033[1;31m# Dot Chart 1 ------\033[0m ", '\n') 
cat("  dotchart(mtcars$mpg, ", '\n')
cat("     labels=row.names(mtcars), ", '\n')
cat("     cex=.7,  ", '\n')
cat("     main='Gas Mileage for Car Models',  ", '\n')
cat("     xlab='Miles Per Gallon') ", '\n')
cat("   ", '\n')
cat("\033[1;31m# Dot Chart 2 ------\033[0m ", '\n') 
cat("  x <- mtcars[order(mtcars$mpg),]  ", '\n')
cat("  x$cyl <- factor(x$cyl)  ", '\n')
cat("  x$color[x$cyl==4] <- 'red'  ", '\n')
cat("  x$color[x$cyl==6] <- 'blue' ", '\n')
cat("  x$color[x$cyl==8] <- 'darkgreen' ", '\n')
cat("  dotchart(x$mpg,  ", '\n')
cat("      labels = row.names(x), ", '\n')
cat("      cex=.7,  ", '\n')
cat("      groups = x$cyl,  ", '\n')
cat("      gcolor = 'black',  # group color ", '\n')
cat("      color = x$color, ", '\n')
cat("      pch=19, ", '\n')
cat("      main = 'Gas Mileage for Car Models_grouped by cylinder',  ", '\n')
cat("      xlab = 'Miles Per Gallon') ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("# Vertical and Horizontal lines ------------ ", '\n')
cat("library(ggplot2)  ", '\n')
cat("  ggplot(mtcars, aes(x=wt, y=mpg)) +   ", '\n')
cat("    geom_point() +  ", '\n')
cat("    geom_hline(yintercept=20, color='red', size=1, lty='dashed') +  ", '\n')
cat("    geom_vline(xintercept=3.5, color='blue', size=1, lty='dotted') +  ", '\n')
cat("    theme_bw()  ", '\n')
cat("   ", '\n')
cat("  ggplot(mtcars, aes(x=wt, y=mpg)) +   ", '\n')
cat("    geom_point() +  ", '\n')
cat("    geom_abline(intercept=25, slope = -0.8, col='red', size=1, lty='solid') +   ", '\n')
cat("    theme_bw()  ", '\n')

}}


