e_logit<-function(explaining=0){
if(explaining==0) {
cat("  library(gmodels); library(aj412s) ", '\n')
cat("  df<-BasicData # BasicData는 aj412s의 내장데이터 ", '\n')
cat("  \033[1;36m# R의 오리지널 logit명령문은  길고 복잡해서 logit을 만들었어요  \033[0m", '\n')
cat("  결과 <- logit(debt2 ~ conv + satprice + gender, data=df) ", '\n')
cat("  ", '\n')
cat("  \033[1;36m# 단, logit명령문을 사용하면 subset옵션을 사용할 수 없어요  \033[0m", '\n')
cat("  \033[1;36m# subset옵션을 사용하려면 약간 길고 복잡하지만 Original command를 사용합니다 \033[0m", '\n')
cat("  \033[1;36m# age가 5이하이고 edu는 4이하인 레코드만 솎아서 logit분석 하려면 다음과 같이... \033[0m", '\n')
cat("  결과sub <- glm(debt2~conv+satprice+gender, family = binomial(link = 'logit'), data=df, subset=c(age<=5 & edu<=4)) ", '\n')
cat("  ", '\n')
cat("\033[1;36m## 부채보유확률 계산 ------------------------ \033[0m ", '\n')
cat("  아무거나1<-c(1, 3, 4, 1) # 1=상수항, 3=conv, 4=satprice, 1=gender ", '\n')
cat("  아무거나2<-결과$coeff ", '\n')
cat("  sum(아무거나1*아무거나2) ", '\n')
cat("  \033[1;36m# 또는, \033[0m", '\n')
cat("  sum(c(1,3,4,1)*결과$coeff) ", '\n')
cat("  ... ", '\n')
cat("  아무거나3 <- sum(c(1,3,4,1)*결과$coeff) ", '\n')
cat("  Result_exp <- exp(아무거나3) ", '\n')
cat("  부채보유_확률 <- Result_exp/(1+Result_exp)*100 ", '\n')
cat("  ... ", '\n')
cat("  \033[1;36m# 또는, aj412s::logit_prob()를 사용하면 간단히 확률 계산할 수 있어요  \033[0m ", '\n')
cat("  logit_prob(결과, 아무거나1) ", '\n')
cat("  \033[1;36m# 계산된 확률을 tmp란 변수에 저장하려면 다음과 같이...   \033[0m ", '\n')
cat("  tmp<-logit_prob(결과, 아무거나1) ", '\n')
}}

