e_mlogit<-function(explaining=0){
if(explaining==0) {
cat(" \033[1;34m## multinomial logit 분석 ------ \033[0m", '\n')
cat(" library(nnet); library(dplyr); library(bss2) ", '\n')
cat(" ", '\n')
cat(" set.seed(123) ", '\n')
cat(" n <- 1000 ", '\n')
cat(" data <- data.frame( ", '\n')
cat(" debt_type = sample(c('부채없음', '저당대출', '신용대출', '가족대출'), n, replace = TRUE), ", '\n')
cat(" gender = sample(c('남성', '여성'), n, replace = TRUE), ", '\n')
cat(" age = sample(20:70, n, replace = TRUE), ", '\n')
cat(" income = rnorm(n, mean = 5000, sd = 2000) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;31m# Base가 될 독립변수의 유형 지정 --------- \033[0m", '\n')
cat(" data$debt_type<-as.factor(data$debt_type) ", '\n')
cat(" data$debt_type <- relevel(data$debt_type, ref = '부채없음') ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# multinom 모델 적합 --------- \033[0m", '\n')
cat(" result <- multinom(debt_type ~ gender + age + income, data = data, subset=c(gender==1)) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 분석결과 보기 --------- \033[0m", '\n')
cat(" summary_mlogit(result) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 소득변화에 따른 확률을 보기 위한 임의 자료 -------- \033[0m", '\n')
cat(" new_data <- data.frame( ", '\n')
cat(" gender = rep('남성', 61), ", '\n')
cat(" age = rep(30, 61), ", '\n')
cat(" income = seq(2000, 8000, 100) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 확률 계산 --------- \033[0m", '\n')
cat(" prob_result <- mlogit_prob(model, new_data) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# 결과 출력 --------- \033[0m", '\n')
cat(" print(prob_result) ", '\n')
cat(" ", '\n')
}}
