e_mlogit<-function(explaining=0){
if(explaining==0) {
cat(" \033[1;34m## multinomial logit Analysis ------ \033[0m", '\n')
cat(" library(nnet); library(dplyr); library(bss2) ", '\n')
cat(" ", '\n')
cat(" set.seed(123) ", '\n')
cat(" n <- 1000 ", '\n')
cat(" data <- data.frame( ", '\n')
cat(" debt_type = sample(c('부채없음', '부채1', '부채2', '부채3'), n, replace = TRUE), ", '\n')
cat(" gender = sample(c('남', '여'), n, replace = TRUE), ", '\n')
cat(" age = sample(20:70, n, replace = TRUE), ", '\n')
cat(" income = rnorm(n, mean = 5000, sd = 2000) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;31m# Defining base value of dependent variable  --------- \033[0m", '\n')
cat(" data$debt_type<-as.factor(data$debt_type) ", '\n')
cat(" data$debt_type <- relevel(data$debt_type, ref = '부채없음') ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# multinom fitting model --------- \033[0m", '\n')
cat(" result <- multinom(debt_type ~ age + income, data = data ) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# Result --------- \033[0m", '\n')
cat(" summary_mlogit(result) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# Example data to check changing probabilities with changing incomes -------- \033[0m", '\n')
cat(" new_data <- data.frame( ", '\n')
cat(" gender = rep('남', 61), ", '\n')
cat(" age = rep(30, 61), ", '\n')
cat(" income = seq(2000, 8000, 100) ", '\n')
cat(" ) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# calculating probabilities --------- \033[0m", '\n')
cat(" prob_result <- mlogit_prob(result, new_data) ", '\n')
cat(" ", '\n')
cat(" \033[1;34m# Printing results --------- \033[0m", '\n')
cat(" print(prob_result) ", '\n')
cat(" ", '\n')
}}
