e_stat<-function(explaining=0){
if(explaining==0) {
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;31m## 자료의 Sampling -------\033[0m ", '\n')
cat("  index<-sample(nrow(Adata), 6, replace=F) ", '\n')
cat("  Adata[index , ] ", '\n')
cat("   ", '\n')
cat("\033[1;31m## wald test ------ \033[0m  ", '\n')
cat("  fit<-lm(inc~debt+house+spouse2, data=Adata) ", '\n')
cat("  linearHypothesis(fit, c('debt=3', 'spouse2+debt3<=10')) ", '\n')
cat("  linearHypothesis(fit, c('debt=spouse2')) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## NA미싱데이터를 삭제하지 않은 자료에 NA가 있으면, na.rm=T 사용 ------- \033[0m  ", '\n')
cat("  mean(df$inc, na.rm=T)  ", '\n')
cat("  sd(df$inc, na.rm=T) ", '\n')
cat("  library(dplyr) ", '\n')
cat("  df%>%summarize(평균=mean(inc, na.rm=T)) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;31m## 기술통계 with jmv ------- \033[0m ", '\n')
cat("  library(aj412s) ", '\n')
cat("  df<-BasicData ", '\n')
cat("  df$gender<-as.factor(df$gender) ", '\n')
cat("   ", '\n')
cat("jmv::descriptives(  ", '\n')
cat("  data = df, ", '\n')
cat("  vars = c(gender, inc, debt), ", '\n')
cat("  skew = FALSE,  ", '\n')
cat("  kurt = FALSE, ", '\n')
cat("  freq = TRUE, ", '\n')
cat("  bar = TRUE, ", '\n')
cat("  dens = TRUE, ", '\n')
cat("  hist = TRUE, ", '\n')
cat("  violin = TRUE) ", '\n')
cat(" ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;31m## 회귀분석 formula ------- \033[0m", '\n')
cat("  결과<-lm(소득~ . , data=Ada)   \033[1;31m모든변수 선택\033[0m ", '\n')
cat("  결과<-lm(소득~ . -1 - 학교소속감, data=Ada)   \033[1;31m변수제외\033[0m  ", '\n')
cat("  결과<-lm(소득~ 학교소속감:성별, data=Ada)   \033[1;31m상호작용항\033[0m  ", '\n')
cat("  결과<-lm(소득~ 학교소속감 * 성별, data=Ada)   \033[1;31m모든변수 + 모든상호작용\033[0m  ", '\n')
cat("  결과<-lm(소득~ I(학업탈진+성별-10), data=Ada)   \033[1;31m괄호내 수식에 따라 변수 생성\033[0m  ", '\n')
cat("   ", '\n')
cat("\033[1;31m##확률 및 p값 --------\033[0m ", '\n')
cat("  t분포 경계값: qt(확률, n-1)  ", '\n')
cat("  \033[1;93mt분포 p값찾기\033[0m: 1-pt(t검정통계량, n-1)  ", '\n')
cat("  카이자승 경계값: qchisq(확률, 자유도)  ", '\n')
cat("  \033[1;93m카이자승 p값찾기\033[0m: 1-pchisq(카이자승_검정통계량, 자유도)  ", '\n')
cat("  F분포 경계값: qf(확률, 자유도1, 자유도2)  ", '\n')
cat("  \033[1;93mF분포 p값찾기\033[0m: 1-pf(F검정통계량, k-1, n-k)  ", '\n')
cat("  정규분포 확률 : pnorm(z검정통계량)  ", '\n')
cat("  정규분포 경계값: qnorm(확률)  ", '\n')
cat("  \033[1;93m정규분포 p값찾기\033[0m: 1-pnorm(z검정통계량)  ", '\n')
cat("   ", '\n')

} }

